useDotenv: true
service: edge-locations-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: GET

  read:
    handler: read.handler
    events:
      - httpApi:
          path: /v1/read
          method: GET
  create:
    handler: create.handler
    events:
      - httpApi:
          path: /v1/create
          method: POST
  delete:
    handler: delete.handler
    events:
      - httpApi:
          path: /v1/delete
          method: DELETE
