service: edge-locations-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  environment:
    DATABASE_URL: ${file(.env.json):DATABASE_URL}

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: GET
  read:
    handler: read.handler
    events:
      - httpApi:
          path: /read
          method: GET
  create:
    handler: create.handler
    events:
      - httpApi:
          path: /create
          method: POST
  delete:
    handler: delete.handler
    events:
      - httpApi:
          path: /delete
          method: DELETE
