name: Deploy AWS Lambda
env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Deploy
        run: |
          npm install
          npm run deploy
